// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"github.com/projects/watch-list/server/core/domain/interfaces"
	"github.com/projects/watch-list/server/core/users/controller"
	"github.com/projects/watch-list/server/core/users/repository"
	"github.com/projects/watch-list/server/core/users/service"
	"github.com/projects/watch-list/server/database"
)

// Injectors from wire.go:

func Wire(db *database.DbCluster) (interfaces.UserController, error) {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	return userController, nil
}
